### ISSUE TITLE
Miskolc

### ISSUE THREAD

**Issue by urbalazs** [vasony/osm-gimmisn-reference#30]
Sok utca hiányzik a referenciából. Remélhetőleg [ez a lista](https://www.miskolc.hu/sites/default/files/aktualitas/csatolmany/2020-03-06/73298/ovodai_korzetek_utcalista_2020marc.pdf) segít csökkenteni a számot.

**Comment by vasony** [comment]
1185 utca található az óvodai körzet listában, 1200 utca található a referenciában.
23 utca nem található a referenciában, a 226 utcát jelentősen nem fogja csökkenteni, megnézem az eltéréseket, hogy bármit fel tudok-e venni ebből, vagy ezek csak elírások.

**Comment by vasony** [comment]
Az alábbiakat tudtam hozzáadni
- Cementgyári utca
- Kohász utca
- Lyukóvölgy dűlő - Lyukóvölgy van (inkább városrész), de a listában külön van dűlő is
- Pálya dűlő
- Sportliget utca
- Szűcs Sámuel utca - van Szűcs Sándor is, ezúton gratulálok
- Tizenegyedik utca
- Völgy utca

Hiányzik, de nem adtam hozzá csak azért, hogy kiszűrjük
- MÁV 6-os őrház -> nem igazi utca
- Ómassa telep - Ómassa utca van, szerintem ugyanaz, hiába van mindkettő az óvoda körzetben. Ómassa 1 utcás városrész.
- Földes Ferenc utca -> megváltozott
- Szondy György telep -> megváltozott/megszűnt
- Úttörő utca -> megváltozott
- Ságvári Endre telep -> valószínű megváltozott/megszűnt

**Comment by vasony** [comment]
https://www.miskolc.hu/varoshaza/onkormanyzat/dokumentumtar?kategoria=331&keyword=k%C3%B6zter%C3%BClet

56/2019. (VI.20.) számú határozatból
- Vörösmarty Mihály tér
- Bodótetői út

118/2019. (XII.19.) számú határozatból
- Cseres út
- Kiscsászár dűlő
- Szarkahegy - Orgona dűlő	
- Szarkahegy - Rózsa dűlő		
- Szarkahegy - Dália dűlő		
- Advent tér			
- Bíró László utca		
- Zsombékos utca			
- Dinnyés utca			
- Szentbenedekhegyi dűlő		
- Körtés utca			
- Géza sétány			

149/2020 (XI.27) számú határozatból
- Kozák Imre utca

219/2021 (IV.01) számú határozatból
- Alsó kertek utca
- Kastély köz
- Szent Márton dűlő

463/2021. (XI.25.) számú határozatból
- Régi vasút dűlő
- Aranykalász utca
- Szűrszabó utca

**Comment by vasony** [comment]
IV-74/73.251/2000. sz. határozatból

2. Balázs Győző tér elnevezést kapja.
4. Deborah sétány elnevezést kapja.

VIII-125/271.580/2015. sz. határozatból

1. Apostol Bertalan tér elnevezést

[egészségügyi alapellátási körzetek](https://net.jogtar.hu/rendelet?council=miskolc&dbnum=549&docid=A1600030.MIS&searchUrl=/rendelet-kereso/gyors%3Fcouncil%3Dmiskolc%26publisher%3DMIS0)

1660 utca, sok eltérő írásmód, ezért a minőség kétséges -> csak az osm-ben létezők

1. Akác utca
2. Bartók Béla tér
3. Búzavirág dűlőút
4. Európa tér
5. Fasor utca
6. Gubás utca
7. Kiss László dűlő
8. Orsó utca
9. Pünkösdhegy utca
10. ...

**Comment by vasony** [comment]
226 -> 121, most elfáradtam ebben, marad így. ha van még értelmes forrás, akkor nyisd vissza
