### ISSUE TITLE
Gödöllő

### ISSUE THREAD

**Issue by urbalazs** [vasony/osm-gimmisn-reference#31]
A gödöllői további utcák listája nagy mértékben csökkenthető lenne [ezzel a refereinciával](https://www.dai.edu.hu/wp-content/uploads/2021/03/Godolloi-iskolak-korzethatara.pdf).

**Comment by vasony** [comment]
ref: 399 utca, iskola körzet: 431 utca. 
eltérés: 53 utca

**Comment by vasony** [comment]
Felvettem
- Aradi utca
- Aranka utca
- Bagoly utca
- Berkenye utca
- Birs utca
- Cserjés köz
- Csonkás köz
- Déri Miksa utca
- Érsek utca
- Felső-tó utca
- Fodor köz
- Fogadalom utca
- Fürj utca
- Gida köz
- Hamvay Ferenc utca
- Hegyalja utca
- Héja utca
- Hérics köz
- Jázmin utca
- Jogar utca
- Kankalin utca
- Kilátó utca
- Kiss-Komlós utca
- Kökörcsin köz
- Nádor köz
- Nagyváthy János utca
- Ölyv utca
- Őrösi Pál Zoltán sétány
- Pereszke utca
- Repkény utca
- Sólyom utca
- Székely köz
- Tél köz
- Topolya utca
- Venyige utca
- Viola utca

Nem vettem fel
- Tessedik Sámuel Kollégium

**Comment by vasony** [comment]
A képviselő-testület a gödöllői 1159/41 helyrajzi számú közterületet Francsek Imre építészről, a gödöllői 1159/66 helyrajzi számú közterületet Medgyaszay István építészről, valamint a gödöllői 4427/2, valamint a 4427/5 helyrajzi számú közterületeket Meggyes köznek nevezte el.

**Comment by vasony** [comment]
57 -> 10
