### ISSUE TITLE
Budapest 22: referenciában nem szereplő házszámok

### ISSUE THREAD

**Issue by urbalazs** [vasony/osm-gimmisn-reference#9]
Két házszámot találtam, amelyek hiányoznak a referenciából:

- 1221 Budapest, Szent István tér 1. [OSM épület](https://www.openstreetmap.org/way/291912147) és [referencia](https://www.budafokteteny.hu/intezmenyek/nadasdy-kalman-alapfoku-muveszeti-es-altalanos-iskola). Azért hiányozhat, mert az egyetlen cím a téren, és se nem lakóház, se nem cég.
- 1225 Budapest, Őszirózsa utca 4. [OSM címpont](https://www.openstreetmap.org/node/8200170280), egyértelműen kint van az épületen, de maga az épület a merőleges Kardvirág utcáról nyílik, így ezt adtam meg fő címként. Mindkettő házszám látható a terepen.

Szerintem érdemes lenne egy külön fájlt nyitni az olyan találatoknak mint ezek, amelyek nincsenek benne semmilyen referenciában.

**Comment by vasony** [comment]
https://github.com/vasony/osm-gimmisn-reference/blob/master/egyedi-cimek.txt

**Comment by vasony** [comment]
Bekerültek a házszámok
